# Generated by Django 2.2 on 2020-12-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
