# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-12-02 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_auto_20201202_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='profile_image',
            field=models.CharField(default='placeholder.jpg', max_length=200),
        ),
    ]
