# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-12-02 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_auto_20201202_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='profile_image',
            field=models.ImageField(default='static/images/placeholder.jpg', upload_to='static/images'),
        ),
    ]
