# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-12-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_auto_20201202_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='subjects_taught',
            field=models.CharField(max_length=5),
        ),
    ]
