# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-12-03 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_auto_20201203_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='subjects_taught',
            field=models.CharField(max_length=200),
        ),
    ]
