# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-12-04 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0006_auto_20201203_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='profile_image',
            field=models.ImageField(default='directories/static/images/placeholder.jpg', upload_to='directories/static/images'),
        ),
    ]
