# Generated by Django 2.2 on 2020-12-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0008_auto_20201204_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, to='directories.Subject'),
        ),
    ]
