# Generated by Django 2.2 on 2020-12-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0009_auto_20201211_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjects_taught',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
