# Generated by Django 2.2 on 2020-12-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0010_auto_20201212_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='Email_address',
            new_name='Email_Address',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='last_name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='phone_number',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='profile_image',
            new_name='Profile_picture',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='room_number',
            new_name='Room_Number',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='subjects_taught',
            new_name='Subjects_taught',
        ),
    ]
