# Generated by Django 2.2 on 2020-12-13 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0011_auto_20201212_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='Subjects_taught',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
