# Generated by Django 2.2 on 2020-12-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0012_auto_20201213_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='Subjects_taught',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
